env:
  - SRC_REPO_SLUG="nurupo/test" SRC_REPO_BRANCH="test3" DST_REPO_BRANCH="build"

script:
  - cp .travis.${DST_REPO_BRANCH}.yml ..
  - git remote rm origin
  - git remote add origin https://$GITHUB_ACCESS_TOKEN@github.com/$TRAVIS_REPO_SLUG > /dev/null 2>&1
  - git remote add upstream https://github.com/$SRC_REPO_SLUG > /dev/null 2>&1
  - git fetch upstream > /dev/null 2>&1
  - git branch -D $DST_REPO_BRANCH || true
  - git checkout -b $DST_REPO_BRANCH upstream/$SRC_REPO_BRANCH
  - mv ../.travis.${DST_REPO_BRANCH}.yml .travis.yml
  - sed -i 's/-m ci_release_publisher/-m ci_release_publisher --travis-instance-com/' .travis/ci_release_publisher_*
  - git config --global user.email "test@example.com"
  - git config --global user.name "nurupo-test"
  - git commit -am "Modify upstream repo for building"
  - git push origin $DST_REPO_BRANCH --force > /dev/null 2>&1
  - #git checkout -b cron-$TRAVIS_BUILD_ID && git push origin cron-$TRAVIS_BUILD_ID > /dev/null 2>&1
  
