sudo: required
dist: trusty
language: python
python:
  - 3.6

services:
  - docker

matrix:
  fast_finish: true
  include:
    - stage: "Build"
      env: JOB="Linux AppImage amd64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh amd64
    - stage: "Build"
      env: JOB="Linux AppImage i386"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh i386
    - stage: "Build"
      env: JOB="Linux AppImage armel"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armel
    - stage: "Build"
      env: JOB="Linux AppImage armhf"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armhf
    - stage: "Build"
      env: JOB="Linux AppImage arm64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh arm64

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: deploy/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: nurupo/test

notifications:
  email: false

# test4
# test3
# test2
# test1
# test0
# test1
# test2
# test3
# test4
# test3
# test2
# test1
# test0
# test1
# test2
# test3
# test4
