sudo: required
dist: trusty
language: python
python:
  - 3.6

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - env: JOB="Linux AppImage arm64-"
    - env: JOB="foo-"
  - env: GITHUB_REPO_SLUG="nurupo-test/test"
  include:
    - stage: "Build"
      env: JOB="Linux AppImage amd64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh amd64
        - .travis/ci_release_publisher_cleanup1.sh
        - .travis/ci_release_publisher_store.sh "$TRAVIS_BUILD_DIR/deploy"
        - .travis/ci_release_publisher_cleanup2.sh
    - stage: "Build"
      env: JOB="Linux AppImage i386"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh i386
        - .travis/ci_release_publisher_cleanup1.sh
        - .travis/ci_release_publisher_store.sh "$TRAVIS_BUILD_DIR/deploy"
        - .travis/ci_release_publisher_cleanup2.sh
    - stage: "Build"
      env: JOB="Linux AppImage armel"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armel
        - .travis/ci_release_publisher_cleanup1.sh
        - .travis/ci_release_publisher_store.sh "$TRAVIS_BUILD_DIR/deploy"
        - .travis/ci_release_publisher_cleanup2.sh
    - stage: "Build"
      env: JOB="Linux AppImage armhf"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armhf
        - .travis/ci_release_publisher_cleanup1.sh
        - .travis/ci_release_publisher_store.sh "$TRAVIS_BUILD_DIR/deploy"
        - .travis/ci_release_publisher_cleanup2.sh
    - stage: "Build"
      env: JOB="Linux AppImage arm64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh arm64
        - #/bin/false
        - .travis/ci_release_publisher_cleanup1.sh
        - .travis/ci_release_publisher_store.sh "$TRAVIS_BUILD_DIR/deploy"
        - .travis/ci_release_publisher_cleanup2.sh
    - stage: "Hm"
      env: JOB="foo"
      script:
        - #/bin/false
        - .travis/ci_release_publisher_cleanup3.sh
    - stage: "Deploy"
      if: type != pull_request
      script:
        - export ARTIFACTS_DIR="$(mktemp -d)"
        - .travis/ci_release_publisher_collect.sh
        - .travis/ci_release_publisher_cleanup4.sh
        - .travis/ci_release_publisher_publish.sh
        - #/bin/false
        - .travis/ci_release_publisher_cleanup5.sh

branches:
  except:
    - # Do not run Travis-CI builds on tags the publishing script creates (will lead to endless (recursive?) publishing)
    - /^ci-.+$/

notifications:
  email: false

