sudo: required
dist: trusty
language: python
python:
  - 3.6

services:
  - docker

matrix:
  fast_finish: true
  include:
    - stage: "Build"
      env: JOB="Linux AppImage amd64"
      script:
        - /bin/false
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh amd64
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Build"
      env: JOB="Linux AppImage i386"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh i386
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Build"
      env: JOB="Linux AppImage armel"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armel
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Build"
      env: JOB="Linux AppImage armhf"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh armhf
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Build"
      env: JOB="Linux AppImage arm64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh arm64
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Build"
      env: JOB="Linux AppImage arm64"
      script:
        - sudo docker run --rm -v $PWD:/repo debian:stretch-slim /bin/bash /repo/.travis/build_linux.sh arm64
        - .travis/deploy_store.sh ./deploy
      after_failure:
        - .travis/deploy_cleanup_store.sh
        - .travis/deploy_cleanup.sh
    - stage: "Deploy"
      if: type != pull_request
      script:
        - .travis/deploy_release.sh

branches:
  except:
    - # Do not run Travis-CI builds on tags the publishing script creates (will lead to endless (recursive?) publishing)
    - /^ci-.+$/

notifications:
  email: false

