sudo: required
dist: trusty
language: python
python:
  - 3.6

services:
  - docker

matrix:
  fast_finish: true
  include:
    - stage: "Build"
      env: JOB="Linux AppImage amd64"
      script:
        - .travis/ci_release_publisher_cleanup1.sh

branches:
  except:
    - # Do not run Travis-CI builds on tags the publishing script creates (will lead to endless (recursive?) publishing)
    - /^ci-.+$/

notifications:
  email: false

